apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: llama-stack-k8s-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - displayName: Llama Stack Distribution
      kind: LlamaStackDistribution
      name: llamastackdistributions.llamastack.io
      version: v1alpha1
  description: LLama stack operator
  displayName: LLama Stack Operator (dev)
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAdnJLH8AAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB+kGBBAMNRudqkIAAAaPSURBVGje7Zl7bFb1Gcc/pxUW22GwUEGYWnbJ9n0rlUiVQQSrc17QTacjMWzO7GbnmBfIwphmMncJ6m6ZyYY4l21xYxuTMZNNFtcE0A1wUJnYvl8IQ0G2KdJxcy3Bjp79sedNTt5UWtrzhn/4JU3f8zvP75zf83tu3+d74NQ4NYY1kqEulDQW+BDwsu21J0uB6mFsfjPwEaC1vr6+uqura83JUKBqiOs+DNQCZwOLgNtOlgWqhnD6NcA0YI/tHuAAcNbJUuC0E3Sb24E7Y90PB5CvB5ptr47rxcBo2/MlPQN8ArgA2G/72YpZQNJ4Sd8HdgN3AEuABtv3hkg78KakuSF/N4DtfcCNmUe1AFMl1QG7gPuAe4FjkiZJ+n3uFpB0NrAR6Aa+kCTJ8mKxeFTSSknn2L7YdrukJ2Ozy4GGsFYPMFrSwgj4J2PjzcAmYGccykFgBfDPSrjQnbH55vD30tgKvJK53g9cFL9/DiwF1gDzqqqqujo7O/skHYq0vbeqqqot5jqBScA84Nu51wFJK4ADtlsHkLsLuMV2c9n8UuAl4HdAHXAPMB+4NeLhLkmzgDHAdtvFvGPAwA2Szs1saowklcl1A+/tZ/222Pi1tp8DXgP6gMuBgqQpkZJrgAmSLs5bgQfDb4uSNks6DHQBC8vktgJvjwDNjj1AaQ3As0BjZKAXganA+iRJnog4+Yak+ZJm5BIDtnsktQDXAxOAQ8AX+wm4kukvBNokjQPOiThps324sbGxqq+vzyF32PaCUtZK0/SOqCW9wCrbuyqGhSRtB75j+9Gy+Y5IqbXATZlbbwJtwCXAGZn5FcBC27szdaYF+LftNZWEEu8G0n7mV4VrTAKuSZLktNjwpwJyfBmYGArOjudskPQ5SZ8F6m0/ATxXkUpcpnRvP/MPA0eB72ZS7hvAL+IvO1ZLWgf8EfgqMAKok7QG+GTUh4q5UAp8xvaP88Q0kqYCPwDGAzNt76mUC+0dKgwfIGG0R3o9CDxQyRj4R/g0FVCiJ/DRXEljKqVAEZhSQYRc6u4aKqXAWmBWoVAYWSEFaivdke0D6tI0vblCCsyO/3W5Z6HARJujOI0ELioVopwy0XkB348A44AptnfkaYElwL8iBrYBz0s6PcfT3wTsACYDLwCP5uZCUernAvfY7gLuDjNPyOn0RwH1wALb3VG5W8IquVjgvGyWqK6u3hLg7uqcTv/6qOTbI6Wuy0CXXBToi/9nAXR0dKTAI8DigU5pkLH1TeCntt+IudFx+z+5YCHbWyTtAz4WLwP4GjAD2CTpvsA2R4BLgVf7YxuiiZkcCHUE8AHg/oitBRnRWwJLbc0lCwUftC8ur7C9ITO/OCiXUWVd2q22V2aecTXwWKDSrNxjEVs9IfeuCOIaYFwwHMNWYGqk0KeAmcBNtv9Uuh8Ny5R45o5AmfMDeuyNAD0X+BHwJeCdAEmSbC0Wi72Z91wC/CpYi1nApbafyVOBdwReuT1O7iu2X3uLNQ3AtYAiOJ+yvfM4Fn4guKdfBlOxH5h1POLrRPqBzjD3lbY/L2k18BCwR9Jvg05ps30kEze7AiIPZnw8Nv9R2yuDKDuWaVeHZ4Gmpqakt7f3deC/wDTbr8TJzYmu66p44V8j8F6Mir0zgrEWeA+wzfafJbUCXwd+Y3uepNuAZbYTSWfEM8ZGDHTn4UIXRs/bCZwOXJ6FEZLOjJ52enCe44OBKO8d2m03S+qOmjI7stIMYFnEya8DsjcA021vzMOFSspeBzwOdEhalCTJI8Vi8ZjtA9EXrzrOISwBPhiXNcBfQoG3ZcS2BJvREpROTV6F7KVo5puSJLkM+BbwUJqmOyUtkjRxCDWsr5/rZcFglCrwjjzR6OMB5KYFZzQ2is+no0J3hlu8EL+PAruTJDmYpmkt8D2gKVwoDaZuPPA8cCZQtH1doVAYkabpeqDL9jV5KjAx4O7fgy7sydxriao6HWiKvN/faM8osDLc8bJQ9sGo5EuDW5o8EMk1FFaiMYpZd7AT6/uTKxQK1Wmanl8WZ82BnzYGi/c+2y9nnn0B8JNg9W4czIePZIjga1xs5AbgD8DDtp8e5No5wBXAz0rKh/VagZsDT7WW0nTFPrPGi2dGVb4KeB14OmLgb+HPR/qxzMg0TScD5wdUuDKq+1rg/hP9ZDssBcpiY06kyPeX9bOv8v8PgaPCNUrjELABWAcsH+yJV0SBt1BoQhSyLHvRC3QAe4e64VPj1Mh5/A9u1H1EJQLQ/gAAAABJRU5ErkJggg==
    mediatype: image/png
  install:
    spec:
      deployments:
      - name: llama-stack-k8s-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: llama-stack-k8s-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: llama-stack-k8s-operator
            spec:
              containers:
              - image: quay.io/llamastack/llama-stack-k8s-operator:latest
                name: manager
                resources: {}
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - llamastack
  - llama
  - ai
  links:
  - name: Llama Stack K8s Operator
    url: https://llama-stack-k8s-operator.domain
  maintainers:
  - email: na@noreply.com
    name: name
  maturity: alpha
  provider:
    name: Local Dev
  version: 0.0.0
